# Generated by Django 5.0.2 on 2024-02-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=4),
            preserve_default=False,
        ),
    ]
